spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/doa?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: WYKYQSPSN@12138
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  type-aliases-package: com.yjlhz.doademo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml