spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/doa?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: WYKYQSPSN@12138
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html


mybatis:
  type-aliases-package: com.yjlhz.doademo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  servlet:
    context-path: /doademo

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

# 日志配置
logging:
  level:
    root: info
    com.yjlhz.doademo: debug